### ISSUE TITLE
P0200 Link

### ISSUE THREAD

**Issue by ear** [SuperV1234/accu2017#1]
Hi! I very much enjoyed your talk!

I was interested in flicking through the proposal you mention regarding the Y combinator and the self-reference of lambdas, so I tried googling for it, to no avail. These things are not easy to find if you don't already know where to look! But this is besides the point :smile:

The issue is that your [current pdf](https://github.com/SuperV1234/accu2017/blob/4bda4c7790237daad5f3a3139835690a03c6d90f/implementing_variant_visitation_using_lambdas/talk.pdf) does _not_ link to the correct site. It points to:

`file:///home/vittorioromeo/OHWorkspace/private2/accu2017/wg21.link/p0200`

I thought the chance of the last bits being an actual link were low but I tried nevertheless and I was rewarded: https://wg21.link/p0200 does indeed work! How pretty.

I suppose the PDF-producing software interpreted it as a relative link instead of an absolute one because of the lack of a scheme (`http://` or `https://`, or maybe even `//`).

Thanks again for the beautiful presentation and for posting the slides here. Toodle-oo :wave:

**Comment by vittorioromeo** [comment]
Thank you! I fixed the issue in 392b072384edcfb10d0dfa7924fa3a65b123877a
